AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*_spec.rb"
